In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('Amazon Sale Report.csv')



df_sample = df.sample(1000, random_state=42)
df_sample.to_csv('sample_data.csv', index=False)

C:\Users\abhin\AppData\Local\Temp\ipykernel_8428\864155037.py:5: DtypeWarning: Columns (0: Unnamed: 22) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('Amazon Sale Report.csv')

In [4]:
df = pd.read_csv('Amazon Sale Report.csv', low_memory=False)


df.columns = df.columns.str.strip()

df = df[['Order ID', 'Date', 'Status', 'Fulfilment', 'Sales Channel',
         'Category', 'Qty', 'Amount', 'ship-state']]

In [5]:
df.head()

,Order ID,Date,Status,Fulfilment,Sales Channel,Category,Qty,Amount,ship-state
0,405-8078784-5731545,04-30-22,Cancelled,Merchant,Amazon.in,Set,0,647.62,MAHARASHTRA
1,171-9198151-1101146,04-30-22,Shipped - Delivered to Buyer,Merchant,Amazon.in,kurta,1,406.00,KARNATAKA
2,404-0687676-7273146,04-30-22,Shipped,Amazon,Amazon.in,kurta,1,329.00,MAHARASHTRA
3,403-9615377-8133951,04-30-22,Cancelled,Merchant,Amazon.in,Western Dress,0,753.33,PUDUCHERRY
4,407-1069790-7240320,04-30-22,Shipped,Amazon,Amazon.in,Top,1,574.00,TAMIL NADU

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 128975 entries, 0 to 128974
Data columns (total 9 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   Order ID       128975 non-null  str
 1   Date           128975 non-null  str
 2   Status         128975 non-null  str
 3   Fulfilment     128975 non-null  str
 4   Sales Channel  128975 non-null  str
 5   Category       128975 non-null  str
 6   Qty            128975 non-null  int64
 7   Amount         121180 non-null  float64
 8   ship-state     128942 non-null  str
dtypes: float64(1), int64(1), str(7)
memory usage: 8.9 MB

In [7]:
df.describe()

                 Qty         Amount
count  128975.000000  121180.000000
mean        0.904431     648.561465
std         0.313354     281.211687
min         0.000000       0.000000
25%         1.000000     449.000000
50%         1.000000     605.000000
75%         1.000000     788.000000
max        15.000000    5584.000000